### ISSUE TITLE
vanillaExtractPlugin not working in vite.config.ts

### ISSUE THREAD

**Issue by n8sabes** [wmertens/styled-vanilla-extract#12]
**WORKS** (but not HMR)
`import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';`

**DOES NOT WORK AT ALL** (as defined in the docs)
`import { vanillaExtractPlugin } from 'styled-vanilla-extract/vite';`

_Not sure when it broke, but I am using the main branch._
```json
    "@builder.io/qwik": "github:builderio/qwik-build",
    "@builder.io/qwik-city": "github:builderio/qwik-city-build",
```

**Comment by wmertens** [comment]
Does this work in the 5.5.0-0 prerelease? It does for me.

**Comment by wmertens** [comment]
Going to close this, I assume it's working :)
