### ISSUE TITLE
When using with qwik ssg, break html generation

### ISSUE THREAD

**Issue by olup** [wmertens/styled-vanilla-extract#15]
Content is not included in the initial html

**Comment by wmertens** [comment]
Hi @olup, could you make a reproduction? It's easy if you start with https://qwik.new

**Comment by olup** [comment]
~~Can I use this tool to show what is outputed as SSG html files ?~~

To give a bit more context : Every time I insert a "styled" components in my page component, it's not showing in the hard-coded HTML, nor any of its children. I posit they are built and shown once the js file is loaded, but it's not in the HTML. (I mostly use qwik for static site generation, which it is very good at).

**Comment by olup** [comment]
There you go:

https://stackblitz.com/edit/qwik-starter-wadzsa?file=src/routes/index.tsx

It's already clear from running `npm run preview` the styled component is not rendered when it's present running `npm run dev`

**Comment by wmertens** [comment]
Thank you! I'll take a look

**Comment by wmertens** [comment]
Ok this looks like a bug in Qwik. So the original code is

```tsx
import { component$ } from '@builder.io/qwik';
import { H1 } from '~/components/ui/title.css';

export default component$(() => {
  return (
    <>
      <h1>hello</h1>

      {/* Word is shown in dev, but not in preview */}
      <H1>World</H1>
    </>
  );
});
```

The transformed code (prettified and some renames) is

```
import { s as styled } from './q-72d08942.js';
import { d as jsx, f as s, g as n } from './q-b702ae3c.js';
var t = styled('h1', '_1k48nkh0');
const e = () =>
  jsx(
    n,
    {
      children: [
        s('h1', null, null, 'hello', 3, null),
        jsx(t, { children: 'World' }, 3, 'H1_0'),
      ],
    },
    1,
    'H1_1'
  );
export { e as s_xYL1qOwPyDI };
```

`var t` is the created styled lite component, and as you can see it gets called with `'World'`. The transformed styled creator is:

```js
import { d as jsx } from './q-b702ae3c.js';
const styled = (Tag, myClassName) => {
  const Lite = ({ class: n, ...s }) => {
    let r;
    return (
      ((c) => {
        c &&
          (r || (r = [myClassName]),
          typeof c == 'object'
            ? r.push(
                Object.entries(c)
                  .filter(([, o]) => o)
                  .map(([o]) => o)
                  .join(' ')
              )
            : r.push(c));
      })(n),
      jsx(Tag, { ...s, class: n ? [myClassName, n] : myClassName }, 0, '9E_0')
    );
  };
  return (
    (Lite.class = myClassName),
    Object.defineProperty(Lite, 'className', { get: () => myClassName, enumerable: !1 }),
    (Lite.toString = () => myClassName),
    Lite
  );
};
export { styled as s };
```

as you can see, the lite component will just call `jsx('h1', {children: 'World', class: '_1k48nkh0'}, 0, '9E_0')`. (at least I'm guessing the function is `jsx`).

This should just work. The output html looks like:

```html
<body lang="en">
  <!--qv q:id=2 q:key=e0ss:35_0-->
    <!--qv q:key=zl_1-->
      <!--qv q:id=3 q:key=xYL1:zl_0-->
        <!--qv q:key=H1_1-->
          <h1>hello</h1>
          <!--qv q:key=H1_0-->
          <!--/qv-->
        <!--/qv-->
      <!--/qv-->
    <!--/qv-->
  <!--/qv-->
</body>
```

as you can see, it has room for H1_0 but no content.

I'll open an issue

**Comment by wmertens** [comment]
This was due to #19 and is fixed.
