### ISSUE TITLE
css autocompletion

### ISSUE THREAD

**Issue by realspinelle** [wmertens/styled-vanilla-extract#18]
hello i cant find anywhere in the issues if its something you guys are gonna work on this or not so as an idea to get correct types i found csstype package im currently using that should not cause problem i guess

![image](https://github.com/wmertens/styled-vanilla-extract/assets/39035551/e0d5d679-74d5-4cd4-b8c6-6b9ead6f0282)

**Comment by wmertens** [comment]
Hmm - I just re-export `style` from `@vanilla-extract/css`, and [use their types](https://github.com/wmertens/styled-vanilla-extract/blob/aa37788cedb7bd2c0e361d47c0b4c4795f9293e5/src/ve-style.ts#L15), so it would be better to add csstype support in https://github.com/vanilla-extract-css/vanilla-extract.

You can keep doing it manually of course.

**Comment by wmertens** [comment]
Ah, you might be hitting #20
