### ISSUE TITLE
Get "QWIK WARN Duplicate implementations of "JSXNode" found" when using `styled` function.

### ISSUE THREAD

**Issue by Zhaiyuqing2003** [wmertens/styled-vanilla-extract#19]
### Describe the bug
Using components created by `styled` function in `styled-vanilla-extract/qwik` causing warning `QWIK WARN Duplicate implementations of "JSXNode" found` when start the server using `vite --open --mode ssr`.

### Reproduce the bug

Using `pnpm create qwik@latest` to create a minimal qwik app. Then create file `index.css.ts` under `src/routes` folder. Using the code given in the documentation:

```ts
import { styled } from 'styled-vanilla-extract/qwik'

export const BlueBox = styled.div`
  display: block;
  width: 100%;
  height: 500px;
  background: blue;
`;
```

and modify the `src/routes/index.tsx` to 

```tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { BlueBox } from './index.css';

export default component$(() => {
  return (
    <>
      <h1>Hi 👋</h1>
      <p>
        Can't wait to see what you build with qwik!
        <br />](
        Happy coding.
      </p>
      <Cmp></Cmp>
    </>
  );
});

export const Cmp = component$(() => {
  return <BlueBox />;
});

export const head: DocumentHead = {
  title: "Welcome to Qwik",
  meta: [
    {
      name: "description",
      content: "Qwik site description",
    },
  ],
};

```
(This still follows the Qwik official documentation)

Then start the server by running `npm run start` (or equivalently `vite --open --mode ssr`)

Then the `QWIK WARN Duplicate implementations of "JSXNode" found` will be logged into console.

This warning will exist as long as the `src/routes/index.tsx` uses `<Bluebox />` 

This warning is quite annoying, and I don't know what this warning indicates on my apps (and the possible consequences of it). I don't if this is bug originate from this library or the [Styled-components](https://styled-components.com/) it depends on. For now, I will just use only `style` function.

**Comment by Zhaiyuqing2003** [comment]
For reference, the package.json is
```json
{
  "name": "my-qwik-empty-starter",
  "description": "App with Routing built-in ready to create your app",
  "engines": {
    "node": ">=15.0.0"
  },
  "private": true,
  "scripts": {
    "build": "qwik build",
    "build.client": "vite build",
    "build.preview": "vite build --ssr src/entry.preview.tsx",
    "build.types": "tsc --incremental --noEmit",
    "deploy": "echo 'Run \"npm run qwik add\" to install a server adapter'",
    "dev": "vite --mode ssr",
    "dev.debug": "node --inspect-brk ./node_modules/vite/bin/vite.js --mode ssr --force",
    "fmt": "prettier --write .",
    "fmt.check": "prettier --check .",
    "lint": "eslint \"src/**/*.ts*\"",
    "preview": "qwik build preview && vite preview --open",
    "start": "vite --open --mode ssr",
    "qwik": "qwik"
  },
  "devDependencies": {
    "@builder.io/qwik": "^1.2.6",
    "@builder.io/qwik-city": "^1.2.6",
    "@types/eslint": "8.40.2",
    "@types/node": "^20.4.0",
    "@typescript-eslint/eslint-plugin": "5.61.0",
    "@typescript-eslint/parser": "5.61.0",
    "@vanilla-extract/css": "^1.11.1",
    "eslint": "8.44.0",
    "eslint-plugin-qwik": "^1.2.6",
    "prettier": "2.8.8",
    "styled-vanilla-extract": "^0.5.4",
    "typescript": "5.1.6",
    "undici": "5.22.1",
    "vite": "4.4.0",
    "vite-tsconfig-paths": "4.2.0"
  }
}


```

**Comment by wmertens** [comment]
Yes it's looking like that is a bug with bundling :(

https://github.com/BuilderIO/qwik/issues/4436

**Comment by Zhaiyuqing2003** [comment]
It seems the bundling issue cause some actual problems, for now I guess use only `style` function might be a safer option.

**Comment by brandonpittman** [comment]
I'm getting this error with just the `style` function.

**Comment by wmertens** [comment]
This was fixed recently, it was due to missing a "qwik" attribute in package.json and the qwik component not having ".qwik." in the filename.
