### ISSUE TITLE
`styled` doesn't show types for style objects

### ISSUE THREAD

**Issue by brandonpittman** [wmertens/styled-vanilla-extract#20]
https://github.com/wmertens/styled-vanilla-extract/blob/9701e68164f49e09d26acb5b75c2a45bd5815d01/src/ve-style.ts#L15-L18

If you had this:

```ts
export const GreenButton = styled.button({
  backgroundColor: "green",
  color: "white"
})
```

…you should get autocompletion for CSS properties, but it doesn't show anything.

Also, `StyleRule` could be `ComplexStyleRule` to allow for style objects that include selectors.

<img width="428" alt="CleanShot 2023-08-10 at 6 00 26@2x" src="https://github.com/wmertens/styled-vanilla-extract/assets/967145/345784ff-0005-46f8-8134-beeb094b7ffb">

**Comment by wmertens** [comment]
I see, the union makes StyledParam into `any`. Probably due to the templatestringsarray :-/

**Comment by brandonpittman** [comment]
> I see, the union makes StyledParam into `any`. Probably due to the templatestringsarray :-/

Yeah, I've seen that happen before.

**Comment by wmertens** [comment]
@brandonpittman it seems to be working for me now in 0.5.11
