### ISSUE TITLE
Styled compoents way doesn't seem to work correctly.

### ISSUE THREAD

**Issue by TheAyes** [wmertens/styled-vanilla-extract#24]
Yesterday I've setup some templates which all worked fine a fresh qwik project. Now I'm trying it again and it doesn't seem to be correctly set up as the component get's literally inserted into html.
![image](https://github.com/wmertens/styled-vanilla-extract/assets/68541335/f74466ff-7289-4262-b3b2-5cdb287cd483)
If I do the vanilla-extract way of inserting the object into the class field it works normally however.

This is the code:
![image](https://github.com/wmertens/styled-vanilla-extract/assets/68541335/3ef4207b-2348-46b1-872f-461ee040563f)

**Comment by wmertens** [comment]
It's a component, you have to capitalize the name, so "StyledMessage". If you start the name with lowercase, the JSX transform considers it a regular element like "div".

Enjoy :)

**Comment by TheAyes** [comment]
@wmertens Is there any place I can consider asking styled-vanilla-extract questions, that may not require an entire issue here?
I'm like constantly running into small things I can't find any info about.

**Comment by wmertens** [comment]
@TheAyes come over to the qwik discord, ask in the help channel. I'm often there or others can help too

https://qwikcommunity.com/

**Comment by wmertens** [comment]
@TheAyes come over to the qwik discord, ask in the help channel. I'm often there or others can help too

https://qwikcommunity.com/
