### ISSUE TITLE
styled-vanilla-extract: After modifying the content of xx.css.ts , the project needs to be rebuilt to take effect.

### ISSUE THREAD

**Issue by lontten** [wmertens/styled-vanilla-extract#27]
After modifying the content of xx.css.ts , the project needs to be rebuilt to take effect.
    ndoe: v20.11.1
    win11
    "@builder.io/qwik": "^1.5.1",
    "@builder.io/qwik-city": "^1.5.1",
     "@vanilla-extract/css": "^1.14.1",
    "styled-vanilla-extract": "^0.5.12",

**Comment by calcari** [comment]
Duplicate of #11 
This has been fixed but not released yet

**Comment by JaxCavalera** [comment]
I'm guessing it's still not released based on this comment. Is there anything we can do to help get it released?

**Comment by wmertens** [comment]
apologies, released now, 0.5.13

**Comment by brandonpittman** [comment]
I installed this but still am not getting the updated styles unless I restart the server. Does it need anything else in the Vite config that it didn’t need before?

**Comment by calcari** [comment]
@brandonpittman 
Here is an exemple project : https://github.com/franck-co/styled-vanilla-extract-hot-reload

```
pnpm install
pnpm dev
```
- Change the color in `src/routes/demo.css.ts`
- The text color should change when you save the file

styled-vanilla-extract 0.5.13 + qwik 1.5.7

**Comment by brandonpittman** [comment]
@franck-co Thanks. Will see what’s different with my config.

**Comment by brandonpittman** [comment]
@franck-co @wmertens 

Sorry, my lockfile was acting weird. `package.json` had `.13` but the lock file still had `.12`. Deleted the lockfile and it's working now.
