### ISSUE TITLE
Autocomplete Not Working

### ISSUE THREAD

**Issue by Kesmek** [wmertens/styled-vanilla-extract#5]
Installing `styled-vanilla-extract` into a fresh project with `yarn qwik add styled-vanilla-extract` installs the plugin correctly but the autocomplete is not working as intended. I tested this on the latest versions of qwik and styled-ve. I also checked on the stackblitz that is provided in the README, which also has the same issue.
- Qwik: 0.16.1
- styled-vanilla-extract: 0.5.3

I apologize if this is mentioned anywhere but I couldn't find anywhere mentioning that autocomplete is not supported by this library (since @vanilla-extract/css supports it). Let me know if you need more information.

**Comment by wmertens** [comment]
Ah, you mean that it's not correctly getting the exports from the library? Indeed, it seems that I need to figure that out some more. Thanks for reporting!

**Comment by samwightt** [comment]
@wmertens Just put up a PR that should fix this! The TS types were just a bit off. Should've resolved them.
